const desiredQualityMasterList = [
    "Kind hearted",
    "Empathetic",
    "Good listener",
    "Supportive",
    "Loyal",
    "Mindful",
    "Trustworthy",
    "Respectful",
    "Generous",
    "Compassionate",
    "Funny",
    "Intelligent",
    "Ambitious",
    "Passionate",
    "Adventurous",
    "Affectionate",
    "Genuine",
    "Open minded",
    "Patient",
    "Present",
    "Understanding",
    "Optimistic",
    "Creative",
    "Honest",
    "Faithful",
    "Gentle",
    "Hardworking",
    "Responsible",
    "Independent",
    "Caring",
    "Romantic",
    "Sincere",
    "Flexible",
    "Warm hearted",
    "Thoughtful",
    "Resilient",
    "Positive",
    "Stable",
    "Spontaneous",
    "Artistic",
    "Confident",
    "Communicative",
    "Supportive",
    "Encouraging",
    "Easygoing",
    "Good with children",
    "Family oriented",
    "Health conscious",
    "Well mannered",
    "Good cook",
    "Handy",
    "Educated",
    "Well read",
    "Good taste",
    "Good with finances",
    "Spiritual",
    "Emotionally intelligent",
    "Emotionally stable",
    "Goal oriented",
    "Motivated",
    "Inspirational",
    "Well traveled",
    "Adaptable",
    "Assertive",
    "Charming",
    "Cheerful",
    "Resourceful",
    "Determined",
    "Fair",
    "Grateful",
    "Humorous",
    "Inquisitive",
    "Joyful",
    "Logical",
    "Mature",
    "Nurturing",
    "Organized",
    "Punctual",
    "Reliable",
    "Self aware",
    "Sensitive",
    "Thought provoking",
    "Tolerant",
    "Unselfish",
    "Versatile",
    "Wise",
    "Youthful",
    "Bubbly",
    "Affirming",
    "Balanced",
    "Brave",
    "Charismatic",
    "Diplomatic",
    "Eloquent",
    "Forgiving",
    "Gracious",
    "Impartial",
    "Keen",
    "Logical",
    "Modest",
    "Persistent",
    "Radiant",
    "Self sufficient",
    "Temperate",
    "Upbeat",
    "Vivacious",
    "Wholesome",
    "Xenodochial",
    "Yielding",
    "Zealous"
]

const challengingQualityMasterList = [
    "Selfish",
    "Insecure",
    "Impatient",
    "Dishonest",
    "Insensitive",
    "Lazy",
    "Inconsiderate",
    "Arrogant",
    "Stubborn",
    "Jealous",
    "Manipulative",
    "Critical",
    "Haphazard",
    "Temperamental",
    "Narrow minded",
    "Unreliable",
    "Pessimistic",
    "Overbearing",
    "Indecisive",
    "Vain",
    "Materialistic",
    "Moody",
    "Controlling",
    "Disrespectful",
    "Cynical",
    "Judgmental",
    "Passive aggressive",
    "Stubborn",
    "Defensive",
    "Compulsive",
    "Egotistical",
    "Narcissistic",
    "Overly competitive",
    "Rigid",
    "Sarcastic",
    "Withdrawn",
    "Perfectionist",
    "Inattentive",
    "Manipulative",
    "Irresponsible",
    "Unmotivated",
    "Immature",
    "Addictive personality",
    "Envious",
    "Possessive",
    "Hypocritical",
    "Unforgiving",
    "Distant",
    "Overly critical",
    "Disorganized",
    "Fearful",
    "Gullible",
    "Impulsive",
    "Overly sensitive",
    "Paranoid",
    "Overly emotional",
    "Lazy",
    "Procrastinator",
    "Superficial",
    "Stubborn",
    "Disloyal",
    "Unambitious",
    "Untrustworthy",
    "Insensitive",
    "Spiteful",
    "Rude",
    "Reckless",
    "Uncooperative",
    "Disloyal",
    "Irresponsible",
    "Untidy",
    "Indifferent",
    "Defensive",
    "Cowardly",
    "Short tempered",
    "Weak willed",
    "Bigoted",
    "Nosy",
    "Unpredictable",
    "Nagging",
    "Impulsive",
    "Sloppy",
    "Cruel",
    "Inflexible",
    "Insensitive",
    "Chaotic",
    "Greedy",
    "Overly attached",
    "Scheming",
    "Unreliable",
    "Avoidant",
    "Boastful",
    "Dishonest",
    "Manipulative",
    "Closed minded",
    "Petty",
    "Ungrateful",
    "Self centered"
]